### ISSUE TITLE
代码是不是不太完整？

### ISSUE THREAD

**Issue by Ailerx** [1914669687/ConvUNeXt#1]
作者您好，最近在阅读您的论文，研究了代码，但是代码是不是不完整呀，能否提供预测部分的代码呢，非常感谢

**Comment by 1914669687** [comment]
您好，刚才看了一下，好像确实没有上传predict脚本，需要等到周一才能发您。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月4日(周五) 晚上10:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)




 
能否提供预测部分的代码，谢谢

**Comment by Ailerx** [comment]
好的，麻烦老师了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月4日(周五) 晚上11:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)




 您好，刚才看了一下，好像确实没有上传predict脚本，需要等到周一才能发您。 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年8月4日(周五) 晚上10:54 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1) 
 
 
 
 
   
 能否提供预测部分的代码，谢谢

**Comment by 1914669687** [comment]
同学你好，遗憾的是我原始的代码已经没有了，我也只能去GitHub上看我原始的代码了，哈哈哈哈哈。
但是，我又给你写了一份代码，可以根据你自己的环境试着调试一下。
最后祝你科研顺利哦，多发paper，加油！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1914669687/ConvUNeXt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 晚上11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)





 好的，麻烦老师了。 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年8月4日(周五) 晚上11:33 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1) 
 
 
 
 
  您好，刚才看了一下，好像确实没有上传predict脚本，需要等到周一才能发您。  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年8月4日(周五) 晚上10:54  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)  
   
   
   
   
     
  能否提供预测部分的代码，谢谢

**Comment by Ailerx** [comment]
谢谢老师，代码是上传到GitHub了吗

**Comment by 1914669687** [comment]
在附件里呀，没有收到么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 晚上10:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)




 
谢谢老师，代码是上传到GitHub了吗

**Comment by Ailerx** [comment]
我看了下qq邮箱好像没有哎

**Comment by 1914669687** [comment]
这封邮件呢？我又把附件添加了一遍。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1914669687/ConvUNeXt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月6日(星期天) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)





 
我看了下qq邮箱好像没有哎

**Comment by Ailerx** [comment]
![image](https://github.com/1914669687/ConvUNeXt/assets/134823038/847487c8-3b43-45bf-8c65-8211dbe90c47)
我在邮件里没有找到附件。

**Comment by Ailerx** [comment]
老师，这是我的qq邮箱2635661840@qq.com

**Comment by Ailerx** [comment]
麻烦老师了，非常感谢

**Comment by Ailerx** [comment]
老师，我还有个问题，就是predict部分，是只保存预测图片，不用保存那个MIou和Dice参数吗

**Comment by 1914669687** [comment]
train的时候会显示的，每一轮都会显示miou和dice系数



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)




 
老师，我还有个问题，就是predict部分，是只保存预测图片，不用保存那个MIou和Dice参数吗

**Comment by Ailerx** [comment]
论文里对比提到的MIou和Dice参数，就是train.py运行生成的参数，是吧，
![image](https://github.com/1914669687/ConvUNeXt/assets/134823038/09d636a1-b8b3-4550-a0db-1c27d34aa41e)

**Comment by 1914669687** [comment]
对的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 晚上10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1914669687/ConvUNeXt] 代码是不是不太完整？ (Issue #1)




 
论文里对比提到的MIou和Dice参数，就是train.py运行生成的参数，是吧，

**Comment by Ailerx** [comment]
好的老师，我明白啦，非常感谢您的指导
